//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rpo.ApiServices.Api.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("587")]
        public int SmtpPort {
            get {
                return ((int)(this["SmtpPort"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SmtpAuthenticationEnabled {
            get {
                return ((bool)(this["SmtpAuthenticationEnabled"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SmtpUseSSl {
            get {
                return ((bool)(this["SmtpUseSSl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Documents")]
        public string UploadedDocumentPath {
            get {
                return ((string)(this["UploadedDocumentPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UploadedDocuments/ContactDocuments")]
        public string ContactDocumentPath {
            get {
                return ((string)(this["ContactDocumentPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UploadedDocuments/ComanyDocuments")]
        public string ComanyDocumentPath {
            get {
                return ((string)(this["ComanyDocumentPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UploadedDocuments/ContactImages")]
        public string ContactImagePath {
            get {
                return ((string)(this["ContactImagePath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UploadedDocuments/EmployeeDocument")]
        public string EmployeeDocumentPath {
            get {
                return ((string)(this["EmployeeDocumentPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UploadedDocuments/RFPAttachments")]
        public string RFPAttachmentsPath {
            get {
                return ((string)(this["RFPAttachmentsPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string TaskReminderSchedulerStart {
            get {
                return ((string)(this["TaskReminderSchedulerStart"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string RFPInDraftNotifyAdminSchedulerStart {
            get {
                return ((string)(this["RFPInDraftNotifyAdminSchedulerStart"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public string RfpTwoDaysInDraftUserSchedulerMinute {
            get {
                return ((string)(this["RfpTwoDaysInDraftUserSchedulerMinute"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UploadedDocuments/CompanyAttachments")]
        public string CompanyAttachmentsPath {
            get {
                return ((string)(this["CompanyAttachmentsPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UploadedDocuments/ContactAttachments")]
        public string ContactAttachmentsPath {
            get {
                return ((string)(this["ContactAttachmentsPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UploadedDocuments/JobTrasmittalAttachments")]
        public string JobTrasmittalAttachmentsPath {
            get {
                return ((string)(this["JobTrasmittalAttachmentsPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("07")]
        public string TaskReminderSchedulerHour {
            get {
                return ((string)(this["TaskReminderSchedulerHour"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("03")]
        public string TaskReminderSchedulerMinute {
            get {
                return ((string)(this["TaskReminderSchedulerMinute"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("07")]
        public string RFPInDraftNotifyAdminSchedulerHour {
            get {
                return ((string)(this["RFPInDraftNotifyAdminSchedulerHour"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("08")]
        public string RFPInDraftNotifyAdminSchedulerMinute {
            get {
                return ((string)(this["RFPInDraftNotifyAdminSchedulerMinute"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string RfpTwoDaysInDraftUserSchedulerStart {
            get {
                return ((string)(this["RfpTwoDaysInDraftUserSchedulerStart"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("07")]
        public string RfpTwoDaysInDraftUserSchedulerHour {
            get {
                return ((string)(this["RfpTwoDaysInDraftUserSchedulerHour"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string RfpTwoDaysSubmittedUserSchedulerStart {
            get {
                return ((string)(this["RfpTwoDaysSubmittedUserSchedulerStart"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("07")]
        public string RfpTwoDaysSubmittedUserSchedulerHour {
            get {
                return ((string)(this["RfpTwoDaysSubmittedUserSchedulerHour"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public string RfpTwoDaysSubmittedUserSchedulerMinute {
            get {
                return ((string)(this["RfpTwoDaysSubmittedUserSchedulerMinute"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/UploadedDocuments/ExportedProposal/")]
        public string ProposalFileExportPath {
            get {
                return ((string)(this["ProposalFileExportPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UploadedDocuments/RFPDocuments")]
        public string RFPDocumentPath {
            get {
                return ((string)(this["RFPDocumentPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UploadedDocuments\\JobDocument\\")]
        public string JobDocumentExportPath {
            get {
                return ((string)(this["JobDocumentExportPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("JobDocumentPDFTemplate\\")]
        public string JobDocumentTemplatePath {
            get {
                return ((string)(this["JobDocumentTemplatePath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.20:8085/")]
        public string APIUrl {
            get {
                return ((string)(this["APIUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UploadedDocuments/JobViolationDocuments")]
        public string JobViolationDocumentPath {
            get {
                return ((string)(this["JobViolationDocumentPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UploadedDocuments/TransmittalJobDocuments")]
        public string TransmittalJobDocumentPath {
            get {
                return ((string)(this["TransmittalJobDocumentPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UploadedDocuments/JobDocumentsAttachment")]
        public string JobDocumentAttachmentPath {
            get {
                return ((string)(this["JobDocumentAttachmentPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UploadedDocuments/DOTWorkPermitDocument")]
        public string DOTWorkPermitDocument {
            get {
                return ((string)(this["DOTWorkPermitDocument"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UploadedDocuments/TempDocument")]
        public string TempDocument {
            get {
                return ((string)(this["TempDocument"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UploadedDocuments/TaskDocuments")]
        public string TaskDocumentPath {
            get {
                return ((string)(this["TaskDocumentPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UploadedDocuments/JobTrasmittalPreview")]
        public string JobTrasmittalPreviewPath {
            get {
                return ((string)(this["JobTrasmittalPreviewPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("07")]
        public string CompanyExpiryUpdateSchedulerHour {
            get {
                return ((string)(this["CompanyExpiryUpdateSchedulerHour"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UploadedDocuments/ReportExportToExcel/")]
        public string ReportExcelExportPath {
            get {
                return ((string)(this["ReportExcelExportPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ExportToExcelTemplate/")]
        public string ExportToExcelTemplatePath {
            get {
                return ((string)(this["ExportToExcelTemplatePath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("JobDocumentAddPageTemplate/")]
        public string AddPageTemplatePath {
            get {
                return ((string)(this["AddPageTemplatePath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("vQ2vJ-qfUXIAAAAAAABSXj6jT_W8xojU2uJ7x_o__EE-qv8FxBRD9Dx1Hnc4tz3-")]
        public string DropboxAccessToken {
            get {
                return ((string)(this["DropboxAccessToken"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.dropbox.com/home/COR_JOBDOCS_QA_UAT_LOCAL")]
        public string DropboxExternalUrl {
            get {
                return ((string)(this["DropboxExternalUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/COR_JOBDOCS_QA_UAT_LOCAL/")]
        public string DropboxFolderPath {
            get {
                return ((string)(this["DropboxFolderPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DropboxNamespaceId {
            get {
                return ((string)(this["DropboxNamespaceId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.20:8000/")]
        public string FrontEndUrl {
            get {
                return ((string)(this["FrontEndUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("No")]
        public string IsSnapcor {
            get {
                return ((string)(this["IsSnapcor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("No")]
        public string IsUAT {
            get {
                return ((string)(this["IsUAT"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("smtp.gmail.com")]
        public string SmtpHost {
            get {
                return ((string)(this["SmtpHost"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ithelp@credencys.com")]
        public string SmtpUserName {
            get {
                return ((string)(this["SmtpUserName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cred#123)(*")]
        public string SmtpPassword {
            get {
                return ((string)(this["SmtpPassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("35")]
        public string CompanyExpiryUpdateSchedulerMinute {
            get {
                return ((string)(this["CompanyExpiryUpdateSchedulerMinute"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rposupportgroup@credencys.com;")]
        public string JobViolationUpdateDeveloperEmail {
            get {
                return ((string)(this["JobViolationUpdateDeveloperEmail"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public string JobECBViolationUpdateSchedulerHourMinute {
            get {
                return ((string)(this["JobECBViolationUpdateSchedulerHourMinute"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("55")]
        public string JobViolationUpdateSchedulerHourMinute {
            get {
                return ((string)(this["JobViolationUpdateSchedulerHourMinute"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("posupportgroup@credencys.com;")]
        public string CronjobUpdateDeveloperEmail {
            get {
                return ((string)(this["CronjobUpdateDeveloperEmail"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("India Standard Time")]
        public string CronjobTimeZone {
            get {
                return ((string)(this["CronjobTimeZone"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public string JobDOBViolationUpdateSchedulerHourMinute {
            get {
                return ((string)(this["JobDOBViolationUpdateSchedulerHourMinute"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("35")]
        public string JobDobNowApplicationUpdateSchedulerHourMinute {
            get {
                return ((string)(this["JobDobNowApplicationUpdateSchedulerHourMinute"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("55")]
        public string JobDOBUpdateSchedulerHourMinute {
            get {
                return ((string)(this["JobDOBUpdateSchedulerHourMinute"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("55")]
        public string JobDobApplicationUpdateSchedulerHourMinute {
            get {
                return ((string)(this["JobDobApplicationUpdateSchedulerHourMinute"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("04")]
        public string JobDobApplicationUpdateSchedulerHour {
            get {
                return ((string)(this["JobDobApplicationUpdateSchedulerHour"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("01")]
        public string JobPermitStatusSchedulerHour {
            get {
                return ((string)(this["JobPermitStatusSchedulerHour"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("55")]
        public string JobPermitStatusSchedulerHourMinute {
            get {
                return ((string)(this["JobPermitStatusSchedulerHourMinute"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("04")]
        public string JobECBViolationUpdateSchedulerHour {
            get {
                return ((string)(this["JobECBViolationUpdateSchedulerHour"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("03")]
        public string JobDOBViolationUpdateSchedulerHour {
            get {
                return ((string)(this["JobDOBViolationUpdateSchedulerHour"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("05")]
        public string JobViolationUpdateSchedulerHour {
            get {
                return ((string)(this["JobViolationUpdateSchedulerHour"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("08")]
        public string JobDobNowApplicationUpdateSchedulerHour {
            get {
                return ((string)(this["JobDobNowApplicationUpdateSchedulerHour"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("06")]
        public string JobDOBUpdateSchedulerHour {
            get {
                return ((string)(this["JobDOBUpdateSchedulerHour"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public string JobCustomerReminderSchedulerHour {
            get {
                return ((string)(this["JobCustomerReminderSchedulerHour"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("55")]
        public string JobCustomerReminderSchedulerHourMinute {
            get {
                return ((string)(this["JobCustomerReminderSchedulerHourMinute"]));
            }
        }
    }
}
