// <auto-generated />
namespace Rpo.ApiServices.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Aditional_Group_Grants : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Aditional_Group_Grants));
        
        string IMigrationMetadata.Id
        {
            get { return "201710161108289_Aditional_Group_Grants"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
