// <auto-generated />
namespace Rpo.ApiServices.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Company_NewFields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Company_NewFields));
        
        string IMigrationMetadata.Id
        {
            get { return "201710251618269_Company_NewFields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
