// <auto-generated />
namespace Rpo.ApiServices.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ContactLicense_Number_toString : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ContactLicense_Number_toString));
        
        string IMigrationMetadata.Id
        {
            get { return "201710061754062_ContactLicense_Number_toString"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
