// <auto-generated />
namespace Rpo.ApiServices.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Employee_WillCauseCascadeOnDelete_On_AgentCertificate_And_EmployeeDocument : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Employee_WillCauseCascadeOnDelete_On_AgentCertificate_And_EmployeeDocument));
        
        string IMigrationMetadata.Id
        {
            get { return "201711131811046_Employee_WillCauseCascadeOnDelete_On_AgentCertificate_And_EmployeeDocument"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
