// <auto-generated />
namespace Rpo.ApiServices.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Masters_Grant_GroupAndEmployee : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Masters_Grant_GroupAndEmployee));
        
        string IMigrationMetadata.Id
        {
            get { return "201710311724018_Masters_Grant_GroupAndEmployee"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
