// <auto-generated />
namespace Rpo.ApiServices.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ContactEmailCheckUnique_Remove : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ContactEmailCheckUnique_Remove));
        
        string IMigrationMetadata.Id
        {
            get { return "201811211246450_ContactEmailCheckUnique_Remove"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
