// <auto-generated />
namespace Rpo.ApiServices.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Change_EmailSubjectLength : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Change_EmailSubjectLength));
        
        string IMigrationMetadata.Id
        {
            get { return "201904060711284_Change_EmailSubjectLength"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
