// <auto-generated />
namespace Rpo.ApiServices.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Added_IsAdditionalService_JobfeeSchedule : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_IsAdditionalService_JobfeeSchedule));
        
        string IMigrationMetadata.Id
        {
            get { return "201902181059093_Added_IsAdditionalService_JobfeeSchedule"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
