// <auto-generated />
namespace Rpo.ApiServices.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Increasewidthof2columnsintable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Increasewidthof2columnsintable));
        
        string IMigrationMetadata.Id
        {
            get { return "201905310601096_Increase width of 2 columns in table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
