// <auto-generated />
namespace Rpo.ApiServices.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_column_Serviceitem_contact : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_column_Serviceitem_contact));
        
        string IMigrationMetadata.Id
        {
            get { return "201908070954486_Add_column_Serviceitem_contact"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
