// <auto-generated />
namespace Rpo.ApiServices.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CompanyMasteradd2columnsofDOTInsuranceDisablilityandGeneralLiability : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CompanyMasteradd2columnsofDOTInsuranceDisablilityandGeneralLiability));
        
        string IMigrationMetadata.Id
        {
            get { return "201901281246553_Company Master add 2 columns of  DOT Insurance Disablility and GeneralLiability"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
