// <auto-generated />
namespace Rpo.ApiServices.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Customertable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Customertable));
        
        string IMigrationMetadata.Id
        {
            get { return "202309051327247_Customertable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
